
# Get All
GET http://localhost:3001/books HTTP/1.1
Content-Type: application/json

###
# Create One
POST http://localhost:3001/books HTTP/1.1
Content-Type: application/json

{
  "title": "White Noise"
}
###
# Edit One
PUT http://localhost:3001/books/1 HTTP/1.1
Content-Type: application/json

{
  "title": "Brown Noise"
}

###
# Delete One
DELETE http://localhost:3001/books/1 HTTP/1.1
Content-Type: application/json
